services:
  motopp:
    build: ./motopp/
    command: sh -c "sleep 20 && bash motopp/run.sh"
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'motopp'