apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: omergindes/flask_side
          resources:
          ports:
            - containerPort: 5000
          env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: secret-key
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: mysql-password